language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - MEMCACHED_SERVER=127.0.0.1


matrix:
  fast_finish: true

services:
  - memcached

install:
  - composer require --dev phpstan/phpstan:^0.12

before_script:
  - yes '' | pecl install -f apcu
  - echo "apc.enable_cli=1" > sabrecache.ini
  - echo "extension=memcached.so" >> sabrecache.ini
  - phpenv config-add sabrecache.ini
  - composer install

script:
  - ./bin/php-cs-fixer fix lib/ --dry-run --diff
  - ./bin/phpstan.phar analyse -c phpstan.neon lib
  - ./bin/phpunit --verbose --configuration tests/phpunit.xml
